<a href="https://colab.research.google.com/github/unt-iialab/INFO5731_Spring2020/blob/master/In_class_exercise/In_class_exercise_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **The first In-class-exercise (09/01/2021, 40 points in total)**

(1) Write a Python program to calculate the length of a string. (4 points)

In [1]:
# write your answer here
string = input("Please enter a string: ")
print("The length of the string is " + str(len(string)))

Please enter a string:  hello

The length of the string is 5

(2) Write a Python program to count the number of characters in a string. (4 points)

Sample String : 'google.com‘, 

Expected Result : {'o': 3, 'g': 2, '.': 1, 'e': 1, 'l': 1, 'm': 1, 'c': 1}

In [21]:
# write your answer here
test_str = input("Please enter a string: ")
dict_str = {}
for i in test_str:
  if i in dict_str:
    dict_str[i] += 1
  else:
    dict_str[i] = 1
sorted_str = sorted(dict_str.items(), key=lambda kv:kv[1], reverse = True)
print(sorted_str)

Please enter a string:  google.com

[('o', 3), ('g', 2), ('l', 1), ('e', 1), ('.', 1), ('c', 1), ('m', 1)]

(3) Write a Python program to sum all the items in a list. (4 points)

In [3]:
# write your answer here
items_list=[1,2,3,4,5]
items_list_sum=sum(items_list)
print("The sum of items in the list is " + str(items_list_sum))

The sum of items in the list is 15

(4) Write a Python program to get a string from a given string where all occurrences of its first char have been changed to '\$', except the first char itself. (4 points)

Sample String : 'restart‘, 

Expected Result : 'resta\$t'

In [3]:
# write your answer here
def change_char(str1):  
  char = str1[0]  
  str1 = str1.replace(char, '$')  
  str1 = char + str1[1:]  
  return str1  
print(change_char('restart'))

resta$t

(5) Write a program with python which could accept two parameter a and b to calculate and output the result of S, where 

$\ S=3.14*(1+a/b)^3$ (4 points)

In [35]:
# write your answer here
a = input("Enter the value for a ")
b = input("Enter the value for b ")
S = 3.14*(1+int(a)/int(b))**3
print("The result is " + str(S))

Enter the value for a  4
Enter the value for b  5

The result is 18.312480000000004

(6) Write a Python program to concatenate following dictionaries to create a new one. (4 points)

Sample Dictionary : dic1={1:10, 2:20}, dic2={3:30, 4:40}, dic3={5:50,6:60}, 

Expected Result : {1: 10, 2: 20, 3: 30, 4: 40, 5: 50, 6: 60}

In [33]:
# write your answer here
dic1 = {1:10,2:20}
dic2 = {3:30,4:40}
dic3 = {5:50,6:60}
new_dic = {}
for dictionary in (dic1,dic2,dic3):
  new_dic.update(dictionary)
print(new_dic)

{1: 10, 2: 20, 3: 30, 4: 40, 5: 50, 6: 60}

(7) Write a Python program to check whether an element exists within a tuple. (4 points)

In [6]:
# write your answer here
thistuple = ("apple", "banana", "cherry")
print("The tuple is: " + str(thistuple))
dict_str = input("Please search an element: ")
for i in thistuple:
    if i in dict_str:
        print("Yes, " + i + " is in the tuple.")

The tuple is: ('apple', 'banana', 'cherry')

Please search an element:  apple

Yes, apple is in the tuple.

(8) Write a Python program to find maximum and the minimum value in a set. (4 points)

In [5]:
# write your answer here
this_set = {1,2,3,4,5}
print("Max: " + str(max(this_set)))
print("Min: " + str(min(this_set)))

Max: 5
Min: 1

(9) Write a Python program to randomly divide the students in this class into six groups for term projects, each group should have at least 4 students but no more than 6 students (including 6). Here is the students list: (4 points)

studnet_list = ['vmb0067','pc0353','snd0097','yye0005','sg0940','bk0301','rak0120','rrk0058','spk0057','vl0135','nm0547','pn0159',
           'msp0174','dd0420','ds0761','rs0850','ss1995','at0739','at0768','mv0299','tv0119','dy0091','py0080','ttp0037','hc0439','ri0094','pk0339', 'hn0145','mn0426']

In [9]:
# write your answer here
import random
student_list = ['vmb0067','pc0353','snd0097','yye0005','sg0940','bk0301','rak0120','rrk0058','spk0057','vl0135','nm0547','pn0159',
           'msp0174','dd0420','ds0761','rs0850','ss1995','at0739','at0768','mv0299','tv0119','dy0091','py0080','ttp0037','hc0439','ri0094','pk0339', 'hn0145','mn0426']

for i in range(6):
  n = random.randint(4,6)
  sampling = random.choices(student_list, k=n)
  student_list = [i for i in student_list if i not in sampling]
  print("Group " + str(i+1) + ": ", sampling)

Group 1:  ['dy0091', 'bk0301', 'sg0940', 'rak0120', 'rs0850']
Group 2:  ['vmb0067', 'ss1995', 'mn0426', 'pn0159', 'mn0426', 'pk0339']
Group 3:  ['mv0299', 'tv0119', 'ri0094', 'rrk0058']
Group 4:  ['vl0135', 'spk0057', 'spk0057', 'at0739']
Group 5:  ['py0080', 'ttp0037', 'ds0761', 'py0080', 'pc0353']
Group 6:  ['yye0005', 'hn0145', 'nm0547', 'hc0439']

(10) Write a Python program to find the duplicate elements in a given array of integers. Return -1 If there are no such elements. (4 points)

In [7]:
def duplicate(arr):
  arr_set = set()
  no_duplicate = -1
  for i in range(len(arr)):
    if arr[i] in arr_set:
      return arr[i]
    else:
      arr_set.add(arr[i])
  return no_duplicate

arr_1 = [1,2,3]
arr_2 = [1,2,2]

print("The array 1 is: " + str(arr_1))
print("The array 2 is: " + str(arr_2))

print(duplicate(arr_1))
print(duplicate(arr_2))

The array 1 is: [1, 2, 3]
The array 2 is: [1, 2, 2]
-1
2

(11) Write a Python program to select all the Sundays of a specified year. (4 extra points)

In [11]:
# write your answer here
from datetime import date, timedelta
year = 2021
first_d = date(year, 1, 1)                    
first_d = first_d + timedelta(days = 6 - first_d.weekday())  
while first_d.year == year:
  print(first_d)
  first_d = first_d + timedelta(days = 7)

2021-01-03
2021-01-10
2021-01-17
2021-01-24
2021-01-31
2021-02-07
2021-02-14
2021-02-21
2021-02-28
2021-03-07
2021-03-14
2021-03-21
2021-03-28
2021-04-04
2021-04-11
2021-04-18
2021-04-25
2021-05-02
2021-05-09
2021-05-16
2021-05-23
2021-05-30
2021-06-06
2021-06-13
2021-06-20
2021-06-27
2021-07-04
2021-07-11
2021-07-18
2021-07-25
2021-08-01
2021-08-08
2021-08-15
2021-08-22
2021-08-29
2021-09-05
2021-09-12
2021-09-19
2021-09-26
2021-10-03
2021-10-10
2021-10-17
2021-10-24
2021-10-31
2021-11-07
2021-11-14
2021-11-21
2021-11-28
2021-12-05
2021-12-12
2021-12-19
2021-12-26